
 version: 2
 updates:
   - package-ecosystem: "npm" # See documentation for possible values
     directory: "/ui/client" # Location of package manifests
     schedule:
       interval: "daily"
     labels:
       - "ui"
       - "dependencies"
     open-pull-requests-limit: 20
